### ISSUE TITLE
报错跑不起来

### ISSUE THREAD

**Issue by zikkeung** [xiaotiandada/takeaway#3]
jsEnginScriptError
Component is not found in path "static/dist/row/index" (using by "pages/index/main")
Error: Component is not found in path "static/dist/row/index" (using by "pages/index/main")

**Comment by xiaotiandada** [comment]
> jsEnginScriptError
> Component is not found in path "static/dist/row/index" (using by "pages/index/main")
> Error: Component is not found in path "static/dist/row/index" (using by "pages/index/main")

抱歉没注意GitHub信息提示

组件是需要单独下载的引入的哦~

QAQ
